name: Continuous Integration

on:
  pull_request:
    branches:
      - main
      - workflow-test

jobs:
  build-and-test:
    runs-on: self-hosted
    defaults:
      run:
        shell: powershell
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies for the client
      working-directory: ./client
      run: npm install

    - name: Install dependencies for the server
      working-directory: ./server
      run: npm install

    - name: Start the server
      working-directory: ./server
      run: Start-Process -NoNewWindow -FilePath 'node' -ArgumentList 'server.js'

    - name: Start the client
      working-directory: ./client
      run: Start-Process -NoNewWindow -FilePath 'npm' -ArgumentList 'start'
      timeout-minutes: 2 # Allows time for the client to fully start

    - name: Run Cypress tests
      working-directory: ./client # Assuming your cypress tests are here
      run: npx cypress run

    - name: Kill all node processes
      if: always()
      run: Stop-Process -Name "node" -Force
