name: Continuous Integration

on:
  pull_request:
    branches:
      - main
      - workflow-test

jobs:
  setup-dependencies:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Set Execution Policy
        run: Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
        shell: powershell
      - name: Install server dependencies
        run: |
          cd server
          npm install
        shell: powershell
      - name: Install client dependencies
        run: |
          cd client
          npm install
        shell: powershell 
      - name: Install testing dependencies
        run: |
          cd testing
          npm install
        shell: powershell  

   cypress-tests:
    needs: setup-dependencies
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Set Execution Policy
        run: Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
        shell: powershell
      - name: Install server dependencies
        run: |
          cd server
          npm install
        shell: powershell
      - name: Install client dependencies
        run: |
          cd client
          npm install
        shell: powershell 
      - name: Install testing dependencies
        run: |
          cd testing
          npm install
        shell: powershell  
      - name: List installed packages (Debugging)
        run: |
          cd testing
          npm list
        shell: powershell
      - name: Run Cypress Tests
        run: |
          cd testing
          npx cypress run
        shell: powershell

  jest-tests:
    needs: cypress-tests
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Set Execution Policy
        run: Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
        shell: powershell
      - name: Install server dependencies
        run: |
          cd server
          npm install
        shell: powershell
      - name: Run Jest Tests
        run: |
          cd server
          npm run test
        shell: powershell
