name: Continuous Integration

on:
  pull_request:
    branches:
      - main
      - workflow-test

jobs:
  cypress-tests:
    runs-on: self-hosted  # This job uses the self-hosted runner
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Set Execution Policy
      run: Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process
      shell: powershell
    - name: Install client dependencies
      run: |
        cd client
        npm install
      shell: powershell
    - name: Start client
      run: |
        $env:BROWSER = "none"
        npm start
      working-directory: ./client
      shell: powershell
    - name: Install server dependencies
      run: |
        cd server
        npm install
      shell: powershell
    - name: Start server
      run: |
        $null = node ./server.js
      working-directory: ./server
      shell: powershell
    - name: Wait for servers to start
      run: Start-Sleep -Seconds 10
      shell: powershell
    - name: Install testing dependencies
      run: |
        cd testing
        npm install
      shell: powershell
    - name: Run Cypress Tests
      run: |
        cd testing
        npx cypress run
      shell: powershell

  jest-tests:
    needs: cypress-tests  # Jest tests will wait for Cypress tests to complete
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Set Execution Policy
      run: Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process
      shell: powershell
    - name: Install server dependencies
      run: |
        cd server
        npm install
      shell: powershell
    - name: Run Jest Tests
      run: |
        cd server
        npm run test
      shell: powershell
