name: Continuous Integration

on:
  pull_request:
    branches:
      - main
      - workflow-test

jobs:
  jest-tests:
    runs-on: self-hosted  # Using your own self-hosted runner
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Set Execution Policy
      run: Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process
      shell: powershell
    - name: Install server dependencies
      run: |
        cd ${{ github.workspace }}/server
        npm install
      shell: powershell
    - name: Run Jest Tests
      run: |
        cd ${{ github.workspace }}/server
        npm run test
      shell: powershell

  cypress-tests:
    needs: jest-tests  # Cypress tests will wait for Jest tests to complete
    runs-on: self-hosted  # This job also uses the self-hosted runner
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Set Execution Policy
      run: Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process
      shell: powershell
    - name: Install client dependencies
      run: |
        cd ${{ github.workspace }}/client
        npm install
      shell: powershell
    - name: Install server dependencies
      run: |
        cd ${{ github.workspace }}/server
        npm install
      shell: powershell
    - name: Start client
      run: |
        cd ${{ github.workspace }}/client
        npm start &
      shell: powershell
    - name: Start server
      run: |
        cd ${{ github.workspace }}/server
        node server.js &
      shell: powershell
    - name: Wait for servers to start
      run: sleep 10  # Adjust time as necessary to ensure servers are ready
      shell: bash
    - name: Install testing dependencies and run Cypress
      run: |
        cd ${{ github.workspace }}/testing
        npm install
        npx cypress run
      shell: powershell
